// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4ZIcL6hAgHuJhEoqtCGWSGu1nqpI8eeE',
    appId: '1:99641741564:web:a10394df0e1697d1044779',
    messagingSenderId: '99641741564',
    projectId: 'my-app-dn',
    authDomain: 'my-app-dn.firebaseapp.com',
    storageBucket: 'my-app-dn.appspot.com',
    measurementId: 'G-B1VJRZND81',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl5KhyMqt_tJN-rTrQbUt0tnRCt3A0yHc',
    appId: '1:99641741564:android:ed33b90eb42e54a3044779',
    messagingSenderId: '99641741564',
    projectId: 'my-app-dn',
    storageBucket: 'my-app-dn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtpFxuLb_1KVZLBCCORBwrFieTmgSyblU',
    appId: '1:99641741564:ios:bda3f8c5a7015c72044779',
    messagingSenderId: '99641741564',
    projectId: 'my-app-dn',
    storageBucket: 'my-app-dn.appspot.com',
    iosClientId: '99641741564-mh1tni5u5s618m76me4vg01c9rsdc319.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppDn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtpFxuLb_1KVZLBCCORBwrFieTmgSyblU',
    appId: '1:99641741564:ios:bda3f8c5a7015c72044779',
    messagingSenderId: '99641741564',
    projectId: 'my-app-dn',
    storageBucket: 'my-app-dn.appspot.com',
    iosClientId: '99641741564-mh1tni5u5s618m76me4vg01c9rsdc319.apps.googleusercontent.com',
    iosBundleId: 'com.example.myAppDn',
  );
}
